### ISSUE TITLE
Documentation is Lacking

### ISSUE THREAD

**Issue by cafletezbrant** [francois-a/rnaseqc#2]
I am trying to run RNA-SeQC on one RNA-seq sample. While I can get the program to execute, the program finds no expressed genes, which I find hard to believe. Is there expanded documentation for this tool anywhere? The [Broad page](https://software.broadinstitute.org/cancer/cga/rna-seqc) suggests that documentation does exist, but if you go to the link, [the page does not exist](https://www.broadinstitute.org/cancer/cga/rnaseqc_run). In order to troubleshoot this problem, I think I need to understand a bit more how it works and what it is expecting. Please advise and thank you.

**Comment by agraubert** [comment]
Hello,

Without specifics, I can't provide too much help, but there are two things that come to mind when your sample has 0 gene expression:

1) Make sure that the contig names in your bam match those in the GTF. We run in to this a lot, since our lab is transitioning from hg19 to hg38. If your GTF uses chromosome names starting with "chr" the bam needs to follow suit (and vice versa)
1) Make sure you're using a [collapsed GTF annotation](https://github.com/broadinstitute/gtex-pipeline/tree/master/gene_model). RNA-SeQC will not report accurate results when using a full GTF (with multiple transcripts per gene)

Additionally, I highly recommend switching to [RNA-SeQC version 2](https://github.com/broadinstitute/rnaseqc) as it's a significant improvement from the original version. If you need to compare results with the original RNA-SeQC, use the `--legacy` command line flag in the new version, which will produce results consistent with RNA-SeQC 1.1.9 while still benefiting from the performance increases from the old version.

If you need any assistance with running RNA-SeQC 2, please don't hesitate to open an issue in it's [GitHub repo](https://github.com/broadinstitute/rnaseqc/issues) and I'll do what I can to help out

**Comment by cafletezbrant** [comment]
I did #1 (the old version actually crashes if you don't) and #2. However, I am happy to say that v2 at least is computing non-zero counts of gene expression in legacy mode.

**Comment by agraubert** [comment]
Excellent! If the v2 numbers still don't look right, feel free to open an issue in that repo and I'd be happy to help there
